# Generated by Django 5.2.2 on 2025-08-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_sessionplayer_chat_gpt_prompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSetWall',
        ),
    ]
