# Generated by Django 5.2.2 on 2025-08-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_delete_parametersetwall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParameterSetBarrier',
        ),
    ]
