# Generated by Django 5.2.2 on 2025-08-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_delete_parametersetbarrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetnotice',
            name='parameter_set',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_animation_speed',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_bound_box_percent',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_move_speed',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='avatar_scale',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='cool_down_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='interaction_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='interaction_range',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='token_cents_value',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='tokens_per_period',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='world_height',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='world_width',
        ),
        migrations.DeleteModel(
            name='ParameterSetGround',
        ),
        migrations.DeleteModel(
            name='ParameterSetNotice',
        ),
    ]
