# Generated by Django 5.2.2 on 2025-08-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_remove_parameter_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='hex_color',
        ),
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='start_x',
        ),
        migrations.RemoveField(
            model_name='parametersetplayer',
            name='start_y',
        ),
    ]
