# Generated by Django 5.2.2 on 2025-08-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_remove_parameter_set_player_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterset',
            name='break_frequency',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='break_length',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='period_count',
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='period_length',
        ),
    ]
